services:
    redis:
        image: 'redis:alpine'
        container_name: cinetech-redis
        networks:
            - default

    mysql:
        image: 'mysql:8.0'
        container_name: cinetech-mysql-development
        working_dir: /application
        networks:
            - default
        volumes:
            - 'mysql-data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=cinetech
            - MYSQL_DATABASE=cinetech
            - MYSQL_USER=cinetech
            - MYSQL_PASSWORD=cinetech
        ports:
            - '48005:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: cinetech-nginx
        working_dir: /application
        networks:
            - default
        volumes:
            - './back-end:/application'
            - './back-end/phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '48000:80'

    php-fpm:
        build: back-end/phpdocker/php-fpm
        container_name: cinetech-php-fpm
        working_dir: /application
        networks:
            - default
        volumes:
            - './back-end:/application'
            - './back-end/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './back-end/phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'

networks:
    default:
        name: cinetech-network
volumes:
    mysql-data:
