services:
    redis:
        image: 'redis:alpine'
        container_name: product-manager-redis
        networks:
            - default

    postgres:
        image: 'postgres:16-alpine'
        container_name: product-manager-postgres-development
        working_dir: /application
        networks:
            - default
        volumes:
            - 'postgres-data:/var/lib/postgresql/data'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=product_manager
            - POSTGRES_DB=product_manager
        ports:
            - '48004:5432'

    webserver:
        image: 'nginx:alpine'
        container_name: product-manager-nginx
        working_dir: /application
        networks:
            - default
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '48000:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: product-manager-php-fpm
        working_dir: /application
        networks:
            - default
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'

networks:
    default:
        name: product-manager-network
volumes:
    postgres-data:
